arg0=real(argument0)

if arg0=vk_add
or arg0=vk_alt
or arg0=vk_backspace
or arg0=vk_control
or arg0=vk_decimal
or arg0=vk_delete
or arg0=vk_divide
or arg0=vk_down
or arg0=vk_end
or arg0=vk_enter
or arg0=vk_escape
or arg0=vk_f1
or arg0=vk_f10
or arg0=vk_f11
or arg0=vk_f12
or arg0=vk_f2
or arg0=vk_f3
or arg0=vk_f4
or arg0=vk_f5
or arg0=vk_f6
or arg0=vk_f7
or arg0=vk_f8
or arg0=vk_f9
or arg0=vk_home
or arg0=vk_insert
or arg0=vk_left
or arg0=vk_multiply
or arg0=vk_numpad0
or arg0=vk_numpad1
or arg0=vk_numpad2
or arg0=vk_numpad3
or arg0=vk_numpad4
or arg0=vk_numpad5
or arg0=vk_numpad7
or arg0=vk_numpad8
or arg0=vk_numpad9
or arg0=vk_pagedown
or arg0=vk_pageup
or arg0=vk_pause
or arg0=vk_printscreen
or arg0=vk_right
or arg0=vk_shift
or arg0=vk_space
or arg0=vk_subtract
or arg0=vk_tab
or arg0=vk_up
    {
    if arg0=vk_add{return "+"}
    if arg0=vk_alt{return "Alt"}
    if arg0=vk_backspace{return "Backspace"}
    if arg0=vk_control{return "Ctrl"}
    if arg0=vk_decimal{return "Del"}
    if arg0=vk_delete{return "Delete"}
    if arg0=vk_divide{return "/"}
    if arg0=vk_down{return "Down"}
    if arg0=vk_end{return "End"}
    if arg0=vk_enter{return "Enter"}
    if arg0=vk_escape{return "Esc"}
    if arg0=vk_f1{return "F1"}
    if arg0=vk_f10{return "F1"}
    if arg0=vk_f11{return "F11"}
    if arg0=vk_f12{return "F10"}
    if arg0=vk_f2{return "F2"}
    if arg0=vk_f3{return "F3"}
    if arg0=vk_f4{return "F4"}
    if arg0=vk_f5{return "F5"}
    if arg0=vk_f6{return "F6"}
    if arg0=vk_f7{return "F7"}
    if arg0=vk_f8{return "F8"}
    if arg0=vk_f9{return "F9"}
    if arg0=vk_home{return "Home"}
    if arg0=vk_insert{return "Insert"}
    if arg0=vk_left{return "Left"}
    if arg0=vk_multiply{return "*"}
    if arg0=vk_numpad0{return "0"}
    if arg0=vk_numpad1{return "1"}
    if arg0=vk_numpad2{return "2"}
    if arg0=vk_numpad3{return "3"}
    if arg0=vk_numpad4{return "4"}
    if arg0=vk_numpad5{return "5"}
    if arg0=vk_numpad6{return "6"}
    if arg0=vk_numpad7{return "7"}
    if arg0=vk_numpad8{return "8"}
    if arg0=vk_numpad9{return "9"}
    if arg0=vk_pagedown{return "Pagedown"}
    if arg0=vk_pageup{return "Pageup"}
    if arg0=vk_pause{return "Pause"}
    if arg0=vk_printscreen{return "Prt Scr"}
    if arg0=vk_right{return "Right"}
    if arg0=vk_shift{return "Shift"}
    if arg0=vk_space{return "Space"}
    if arg0=vk_subtract{return "-"}
    if arg0=vk_tab{return "Tab"}
    if arg0=vk_up{return "Up"}
    }
else
    {
    return chr(arg0)
    }