///name_get_chars(str)
if string_count(")",argument[0])
|| string_count("(",argument[0])
|| string_count("!",argument[0])
|| string_count("@",argument[0])
|| string_count("#",argument[0])
|| string_count("$",argument[0])
|| string_count("%",argument[0])
|| string_count("^",argument[0])
|| string_count("&",argument[0])
|| string_count("*",argument[0])
|| string_count("=",argument[0])
|| string_count("+",argument[0])
|| string_count("[",argument[0])
|| string_count("]",argument[0])
|| string_count("{",argument[0])
|| string_count("}",argument[0])
|| string_count(":",argument[0])
|| string_count(";",argument[0])
|| string_count("'",argument[0])
|| string_count('"',argument[0])
|| string_count("?",argument[0])
|| string_count("<",argument[0])
|| string_count(">",argument[0])
|| string_count(" ",argument[0])
{return true}

return false
